---
title: "Homework 2"
author: Lauren Smith
date: September 24, 2019
output: html_document
---
```{r, echo = FALSE, warnings = FALSE}
library(gapminder)
library(tidyverse)
library(dplyr)
```


# Exercise 1.1
```{r, Exercise 1.1}
gapminder %>%
  filter(country == "Canada" | 
         country == "New Zealand" | 
         country == "United States") %>%
  filter(year >= "1970" &
           year <= "1979")
```

# Exercise 1.2
```{r, Exercise 1.2}
gapminder %>%
  filter(country == "Canada" | 
         country == "New Zealand" | 
         country == "United States") %>%
  filter(year >= "1970" &
           year <= "1979") %>%
  select(country, gdpPercap)
```


# Exercise 1.3
```{r, Exercise 1.3}
gap_inc <- gapminder %>%
  arrange(year) %>%
  group_by(country) %>%
  mutate(increaselifeExp = lifeExp -lag(lifeExp)) %>%
  filter(increaselifeExp < 0)
DT::datatable(gap_inc)
```


# Exercise 1.4
```{r, Exercise 1.4}
gapminder %>%
  group_by(country) %>%
  filter(gdpPercap == max(gdpPercap))
```


# Exercise 1.5
```{r, Exercise 1.5 load, echo = FALSE, warnings = FALSE}
library(ggplot2)
library(scales)
```

```{r, Exercise 1.5}
gapminder %>%
  filter(country == "Canada") %>%
  ggplot(aes(lifeExp, gdpPercap)) +
  geom_point(alpha = 0.5) +
  scale_y_log10() +
  labs(title = "GDP per Capita and Life Expectancy", x = "Life Expectancy", y = "Log10 of GDP per Capita") +
  theme(plot.title = element_text(hjust = 0.5))
```


# Exercise 2
## Exploring "Life Expectancy" Variable
```{r, Exercise 2 life Exp1}
range(gapminder$lifeExp)
```
### Plot of the average life expectancy of each continent
```{r, Exercise 2 lifeExp2}
gapminder %>%
  group_by(continent) %>%
  summarise(meanlifeExp = mean(lifeExp)) %>%
  ggplot(aes(continent, meanlifeExp)) +
  geom_bar(stat = "identity") +
  labs(title = "Mean Life Expectancy by Continent", 
       x = "Continent", 
       y = "Mean Life Expectancy") +
  theme(plot.title = element_text(hjust = 0.5))
```


## Exploring "Country" Variable

```{r, Exercise 2 country1}

```
```{r, Exercise 2 country2}

```









